/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_omega_engine_gpu_JNITest */

#ifndef _Included_com_omega_engine_gpu_JNITest
#define _Included_com_omega_engine_gpu_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_omega_engine_gpu_JNITest
 * Method:    max
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_omega_engine_gpu_JNITest_max
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_omega_engine_gpu_JNITest
 * Method:    im2col
 * Signature: ([F[FIIIIIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_omega_engine_gpu_JNITest_im2col
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
